### ISSUE TITLE
Add animation on tabs

### ISSUE THREAD

**Issue by tzi** [nico3333fr/jquery-accessible-tabs-aria#13]
Hi @nico3333fr!

I used this plugin on https://netalis.fr and I had to add a fade in/out animation.

Sadly, to achieve that I had to wrap the content in an extra`div` tag.
Here the code I used, maybe it could help you or someone else:

``` css
.js-tabcontent {
  overflow: hidden;
  visibility: visible;
  opacity: 1;
  transition: visibility 0s 0.4s, opacity 0.4s 0.4s;
}

.js-tabcontent > div {
  transition: margin-top 0s 0.4s;
}

.js-tabcontent[aria-hidden=true] {
  visibility: hidden;
  opacity: 0;
  transition: visibility 0s 0.4s, opacity 0.4s;
}

.js-tabcontent[aria-hidden=true] > div {
  margin-top: -10000px
}
```

Thanks for creating and maintaining this project!
Thomas.
